version: '3'
env:
  POSTGRESQL: ${POSTGRESQL}

tasks:
  migr:
    desc: "Сделать миграцию"
    cmds:
      - |
        read -p "Введите название миграции: " name && \
        goose -dir migrations create "$name" sql
  migr_up:
    desc: "Сделать миграцию"
    cmds:
      - goose -dir migrations postgres "" up
  migr_down:
    desc: "Сделать миграцию"
    cmds:
      - goose -dir migrations postgres "" down